In [40]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [45]:
# Prob Hough transform on camera image

img = cv2.imread('tape_road.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,200,255)
cv2.imwrite('tape_road_edges.jpg',edges)
lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength=160,maxLineGap=10)
print(len(lines))
for line in lines:
    for x1,y1,x2,y2 in line:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imwrite('tape_road_detect.jpg',img)

2


True

In [35]:
# Darkened top half of image to try to remove some details from surrounding environment
# Doesn't work as well as increasing thresholds
img = cv2.imread('tape_road.jpg')
#print(type(img))

#img.shape
# image is 426 tall, 640 wide
for row in range(240):
    for col in range(640):
        for p in range(3):
            img[row][col][p] = img[row][col][p]*0.3
            
cv2.imwrite('tape_road_darkened.jpg',img)
dimg = cv2.imread('tape_road_darkened.jpg')
gray = cv2.cvtColor(dimg,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,100,255)
cv2.imwrite('tape_road_darkened_edges.jpg',edges)

True

In [3]:
# Basic test of imread and imshow
# load and show cat image

img = cv2.imread('cat.jpg')
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
# Test of line detection (plain Hough transform)

img = cv2.imread('road.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imwrite('road_grayscale.jpg',gray)
edges = cv2.Canny(gray,50,150)

lines = cv2.HoughLines(edges,1,np.pi/180,200)
#print(lines)
for line in lines:
    for rho,theta in line:
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a*rho
        y0 = b*rho
        x1 = int(x0 + 1000*(-b))
        y1 = int(y0 + 1000*(a))
        x2 = int(x0 - 1000*(-b))
        y2 = int(y0 - 1000*(a))

        cv2.line(img,(x1,y1),(x2,y2),(0,0,255),2)
        print(x1, " ", y1)

cv2.imwrite('houghlines3.jpg',img)

-1013   74
-1012   99
-1009   160
-1011   128
-1011   130
-1007   184
-990   280
-1012   102
-1013   107
-1012   67
-1000   199
-1016   48
-1000   217
-1012   94
-1012   19
-1007   187
-1007   193
-1008   143
-1012   104
-1013   77
-1006   164
-1015   67
-1009   157
-1008   -39
-1012   97
-1000   238
-1006   162
-1006   178
-1000   197
-1000   201
-1011   123
-1014   55
-1008   -54
-1011   135
-1003   199
-1011   126
-1013   46
-1017   9
-1013   -41
-78   -1025
-1006   167
-1011   12
-1013   26
-1012   40


True

In [21]:
# Test of line detection (prob Hough transform)

img = cv2.imread('road.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imwrite('road_grayscale.jpg',gray)
edges = cv2.Canny(gray,50,150)
cv2.imwrite('road_edges.jpg',edges)
minLineLength = 100
maxLineGap = 10
lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength=100,maxLineGap=10)
print(lines)
for line in lines:
    for x1,y1,x2,y2 in line:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imwrite('houghlines5.jpg',img)

[[[298 499 343 126]]

 [[563 219 609 601]]

 [[538   1 568 253]]

 [[330 228 357   1]]

 [[273 713 311 397]]]


True