In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [ ]:
img = cv2.imread('tape_road.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,200,255)
cv2.imwrite('tape_road_edges.jpg',edges)
lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength=100,maxLineGap=10)

i = 0
maxSlope_ind = 0
maxSlope = 0
maxSlope2_ind = 0
maxSlope2 = 0

for line in lines:
    for x1,y1,x2,y2 in line:
        slope = (y2-y1)/(x2-x1)
        print("slope ", i, " = ", slope)
        if abs(slope)>abs(maxSlope):
            maxSlope2 = maxSlope
            maxSlope2_ind = maxSlope_ind
            maxSlope = slope
            maxSlope_ind = i
        elif abs(slope)>abs(maxSlope2):
            maxSlope2 = slope
            maxSlope2_ind = i
        i = i+1
        
kept_lines = np.stack((lines[maxSlope_ind], lines[maxSlope2_ind]))
for line in kept_lines:
    for x1,y1,x2,y2 in line:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
        
cv2.imwrite('tape_road_kept_lines.jpg',img)

In [55]:
# Prob Hough transform on camera image
# Has increased thresholds

img = cv2.imread('tape_road.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,200,255)
cv2.imwrite('tape_road_edges.jpg',edges)
lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength=160,maxLineGap=10)
print("number of lines: ", len(lines))
print("lines array: ")
print(lines)
print("\nlines dimensions: ", lines.shape)

for line in lines:
    for x1,y1,x2,y2 in line:
        print((y2-y1)/(x2-x1))

# x1_der = derived x-coordinate at y = 206 for line 1
l1_y3 = lines[1][0][3]
l1_x3 = ((l1_y3 - lines[0][0][1])/slopes[0]) + lines[0][0][0]
l1_x3 = l1_x3.astype(int)
print("type(x_der): ", type(l1_x3))
#print(x1_der)

c_line_y1 = l1_y3
c_line_x1 = (l1_x3 + lines[1][0][2])/2
c_line_x1 = c_line_x1.astype(int)
print("c_line_x1: ", c_line_x1)

c_line_y2 = c_line_y1 + 200
l1_x4 = ((c_line_y2 - lines[0][0][1])/slopes[0]) + lines[0][0][0]
l2_x4 = ((c_line_y2 - lines[1][0][1])/slopes[1]) + lines[1][0][0]

c_line_x2 = (l1_x4 + l2_x4)/2
c_line_x2 = c_line_x2.astype(int)

print("type(line2 x2): ", type(lines[1][0][3]))
print("type(c_line_x1): ", type(c_line_x1))

c_line = np.array([[[c_line_x1, c_line_y1, c_line_x2, c_line_y2]]])
print("c_line.shape: ", c_line.shape)
print("c_line array: \n", c_line, "\n")

new_lines = np.append(lines, c_line, axis=0)
print("lines array after append: \n", new_lines, "\n")
#print(new_lines.dtype)

for line in new_lines:
    for x1,y1,x2,y2 in line:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imwrite('tape_road_c_line.jpg',img)

number of lines:  2
lines array: 
[[[310 170 393 425]]

 [[144 373 256 206]]]

lines dimensions:  (2, 1, 4)
3.072289156626506
-1.4910714285714286
type(x_der):  <class 'numpy.int32'>
c_line_x1:  288
type(line2 x2):  <class 'numpy.intc'>
type(c_line_x1):  <class 'numpy.int32'>
c_line.shape:  (1, 1, 4)
c_line array: 
 [[[288 206 254 406]]] 

lines array after append: 
 [[[310 170 393 425]]

 [[144 373 256 206]]

 [[288 206 254 406]]] 



True

In [65]:
# Prob Hough transform on camera image with selecting tape edges
# with print statements

img = cv2.imread('tape_road.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,200,255)
cv2.imwrite('tape_road_edges.jpg',edges)
lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength=100,maxLineGap=10)
print("number of lines: ", len(lines))
print("lines array: ")
print(lines)
print("\nlines dimensions: ", lines.shape)

i = 0
maxSlope_ind = 0
maxSlope = 0
maxSlope2_ind = 0
maxSlope2 = 0


for line in lines:
    for x1,y1,x2,y2 in line:
        slope = (y2-y1)/(x2-x1)
        print("slope ", i, " = ", slope)
        if abs(slope)>abs(maxSlope):
            maxSlope2 = maxSlope
            maxSlope2_ind = maxSlope_ind
            maxSlope = slope
            maxSlope_ind = i
            print("new maxSlope = ", maxSlope, " at i = ", maxSlope_ind)
            print("maxSlope2 = ", maxSlope2, " at i = ", maxSlope2_ind)
        elif abs(slope)>abs(maxSlope2):
            maxSlope2 = slope
            maxSlope2_ind = i
            print("new maxSlope2 = ", maxSlope2, " at i = ", maxSlope2_ind)
        i = i+1
        
print("maxSlope = ", maxSlope, " at index = ", maxSlope_ind)
print("maxSlope2 = ", maxSlope2, " at index = ", maxSlope2_ind)

print(lines[maxSlope_ind])
kept_lines = np.stack((lines[maxSlope_ind], lines[maxSlope2_ind]))
print(kept_lines)

for line in kept_lines:
    for x1,y1,x2,y2 in line:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
        
cv2.imwrite('tape_road_kept_lines.jpg',img)


number of lines:  10
lines array: 
[[[310 170 393 425]]

 [[144 373 256 206]]

 [[  5 202 120 210]]

 [[ 79 218 206 220]]

 [[  0 196 157 196]]

 [[ 20 195 153 167]]

 [[  2 194 164 194]]

 [[122 411 192 299]]

 [[ 27 177 135 162]]

 [[ 55 197 164 170]]]

lines dimensions:  (10, 1, 4)
slope  0  =  3.072289156626506
new maxSlope =  3.072289156626506  at i =  0
maxSlope2 =  0  at i =  0
slope  1  =  -1.4910714285714286
new maxSlope2 =  -1.4910714285714286  at i =  1
slope  2  =  0.06956521739130435
slope  3  =  0.015748031496062992
slope  4  =  0.0
slope  5  =  -0.21052631578947367
slope  6  =  0.0
slope  7  =  -1.6
new maxSlope2 =  -1.6  at i =  7
slope  8  =  -0.1388888888888889
slope  9  =  -0.24770642201834864
maxSlope =  3.072289156626506  at index =  0
maxSlope2 =  -1.6  at index =  7
[[310 170 393 425]]
[[[310 170 393 425]]

 [[122 411 192 299]]]


True

In [ ]:
# x1_der = derived x-coordinate at y = 206 for line 1
l1_y3 = lines[1][0][3]
l1_x3 = ((l1_y3 - lines[0][0][1])/slopes[0]) + lines[0][0][0]
l1_x3 = l1_x3.astype(int)
print("type(x_der): ", type(l1_x3))
#print(x1_der)

c_line_y1 = l1_y3
c_line_x1 = (l1_x3 + lines[1][0][2])/2
c_line_x1 = c_line_x1.astype(int)
print("c_line_x1: ", c_line_x1)

c_line_y2 = c_line_y1 + 200
l1_x4 = ((c_line_y2 - lines[0][0][1])/slopes[0]) + lines[0][0][0]
l2_x4 = ((c_line_y2 - lines[1][0][1])/slopes[1]) + lines[1][0][0]

c_line_x2 = (l1_x4 + l2_x4)/2
c_line_x2 = c_line_x2.astype(int)

print("type(line2 x2): ", type(lines[1][0][3]))
print("type(c_line_x1): ", type(c_line_x1))

c_line = np.array([[[c_line_x1, c_line_y1, c_line_x2, c_line_y2]]])
print("c_line.shape: ", c_line.shape)
print("c_line array: \n", c_line, "\n")

new_lines = np.append(lines, c_line, axis=0)
print("lines array after append: \n", new_lines, "\n")
#print(new_lines.dtype)

In [44]:
# Darkened top half of image to try to remove some details from surrounding environment
# Doesn't work as well as increasing thresholds
img = cv2.imread('tape_road.jpg')
#print(type(img))

#img.shape
# image is 426 tall, 640 wide
for row in range(240):
    for col in range(640):
        for p in range(3):
            img[row][col][p] = img[row][col][p]*0.3
            
cv2.imwrite('tape_road_darkened.jpg',img)
dimg = cv2.imread('tape_road_darkened.jpg')
gray = cv2.cvtColor(dimg,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,100,255)
cv2.imwrite('tape_road_darkened_edges.jpg',edges)

True

In [3]:
# Basic test of imread and imshow
# load and show cat image

img = cv2.imread('cat.jpg')
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
# Test of line detection (plain Hough transform)

img = cv2.imread('road.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imwrite('road_grayscale.jpg',gray)
edges = cv2.Canny(gray,50,150)

lines = cv2.HoughLines(edges,1,np.pi/180,200)
#print(lines)
for line in lines:
    for rho,theta in line:
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a*rho
        y0 = b*rho
        x1 = int(x0 + 1000*(-b))
        y1 = int(y0 + 1000*(a))
        x2 = int(x0 - 1000*(-b))
        y2 = int(y0 - 1000*(a))

        cv2.line(img,(x1,y1),(x2,y2),(0,0,255),2)
        print(x1, " ", y1)

cv2.imwrite('houghlines3.jpg',img)

-1013   74
-1012   99
-1009   160
-1011   128
-1011   130
-1007   184
-990   280
-1012   102
-1013   107
-1012   67
-1000   199
-1016   48
-1000   217
-1012   94
-1012   19
-1007   187
-1007   193
-1008   143
-1012   104
-1013   77
-1006   164
-1015   67
-1009   157
-1008   -39
-1012   97
-1000   238
-1006   162
-1006   178
-1000   197
-1000   201
-1011   123
-1014   55
-1008   -54
-1011   135
-1003   199
-1011   126
-1013   46
-1017   9
-1013   -41
-78   -1025
-1006   167
-1011   12
-1013   26
-1012   40


True

In [52]:
# Test of line detection (prob Hough transform)

img = cv2.imread('tape_road.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,200,255)
cv2.imwrite('tape_road_edges.jpg',edges)
minLineLength = 100
maxLineGap = 10
lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength=100,maxLineGap=10)
print(lines)
for line in lines:
    for x1,y1,x2,y2 in line:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imwrite('houghlines5.jpg',img)

[[[310 170 393 425]]

 [[144 373 256 206]]

 [[  5 202 120 210]]

 [[ 79 218 206 220]]

 [[  0 196 157 196]]

 [[ 20 195 153 167]]

 [[  2 194 164 194]]

 [[122 411 192 299]]

 [[ 27 177 135 162]]

 [[ 55 197 164 170]]]


True